2024-05-09 09:28:29.340 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-18' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<Task pending name='Storage load homeassistant.exposed_entities' coro=<Store._async_load() running at /workspaces/core/homeassistant/helpers/storage.py:296> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[set.remove(), Task.task_wakeup()] created at /workspaces/core/homeassistant/util/async_.py:40> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.129 seconds
2024-05-09 09:28:45.676 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-1' coro=<setup_and_run_hass() running at /workspaces/core/homeassistant/runner.py:156> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[_run_until_complete_cb() at /usr/local/lib/python3.12/asyncio/base_events.py:182] created at /usr/local/lib/python3.12/asyncio/tasks.py:695> took 0.157 seconds
2024-05-09 09:28:46.517 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-1' coro=<setup_and_run_hass() running at /workspaces/core/homeassistant/runner.py:156> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/tasks.py:712> cb=[_run_until_complete_cb() at /usr/local/lib/python3.12/asyncio/base_events.py:182] created at /usr/local/lib/python3.12/asyncio/tasks.py:695> took 0.149 seconds
2024-05-09 09:28:46.734 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-1' coro=<setup_and_run_hass() running at /workspaces/core/homeassistant/runner.py:156> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/tasks.py:712> cb=[_run_until_complete_cb() at /usr/local/lib/python3.12/asyncio/base_events.py:182] created at /usr/local/lib/python3.12/asyncio/tasks.py:695> took 0.112 seconds
2024-05-09 09:28:46.819 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.14 seconds
2024-05-09 09:28:46.821 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.11 seconds
2024-05-09 09:28:46.823 INFO (MainThread) [homeassistant.bootstrap] Setting up frontend, recorder: {'recorder', 'frontend'}
2024-05-09 09:28:46.839 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of isal==1.6.1
2024-05-09 09:28:46.848 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2024-05-09 09:28:46.852 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.00 seconds
2024-05-09 09:28:54.115 INFO (MainThread) [homeassistant.setup] Setting up http
2024-05-09 09:28:54.141 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.03 seconds
2024-05-09 09:28:54.148 INFO (MainThread) [homeassistant.setup] Setting up auth
2024-05-09 09:28:54.158 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.01 seconds
2024-05-09 09:28:54.163 INFO (MainThread) [homeassistant.setup] Setting up config
2024-05-09 09:28:54.183 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.02 seconds
2024-05-09 09:28:54.186 INFO (MainThread) [homeassistant.setup] Setting up diagnostics
2024-05-09 09:28:54.195 INFO (MainThread) [homeassistant.setup] Setup of domain diagnostics took 0.01 seconds
2024-05-09 09:28:54.198 INFO (MainThread) [homeassistant.setup] Setting up file_upload
2024-05-09 09:28:54.200 INFO (MainThread) [homeassistant.setup] Setup of domain file_upload took 0.00 seconds
2024-05-09 09:28:54.206 INFO (MainThread) [homeassistant.setup] Setting up image_upload
2024-05-09 09:28:54.217 INFO (MainThread) [homeassistant.setup] Setup of domain image_upload took 0.01 seconds
2024-05-09 09:28:54.222 INFO (MainThread) [homeassistant.setup] Setting up repairs
2024-05-09 09:28:54.231 INFO (MainThread) [homeassistant.setup] Setup of domain repairs took 0.01 seconds
2024-05-09 09:28:54.235 INFO (MainThread) [homeassistant.setup] Setting up recorder
2024-05-09 09:28:54.249 INFO (MainThread) [homeassistant.setup] Setting up api
2024-05-09 09:28:54.257 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.01 seconds
2024-05-09 09:28:54.262 INFO (MainThread) [homeassistant.setup] Setting up person
2024-05-09 09:28:54.283 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.02 seconds
2024-05-09 09:28:54.291 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2024-05-09 09:28:54.294 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //workspaces/core/config/home-assistant_v2.db was shutdown cleanly
2024-05-09 09:28:54.298 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.01 seconds
2024-05-09 09:28:54.302 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2024-05-09 09:28:54.326 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.02 seconds
2024-05-09 09:28:54.374 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=18 from 2024-05-09 08:48:59.548926)
2024-05-09 09:28:54.405 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.17 seconds
2024-05-09 09:28:54.407 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2024-05-09 09:28:54.410 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.00 seconds
2024-05-09 09:28:54.415 INFO (MainThread) [homeassistant.setup] Setting up search
2024-05-09 09:28:54.416 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.00 seconds
2024-05-09 09:28:54.421 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of home-assistant-frontend==20240501.0
2024-05-09 09:29:19.624 INFO (MainThread) [homeassistant.setup] Setting up frontend
2024-05-09 09:29:19.696 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.07 seconds
2024-05-09 09:29:19.728 WARNING (MainThread) [asyncio] Executing <Task finished name='setup component frontend' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.117 seconds
2024-05-09 09:29:19.748 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 1: {'webhook', 'network', 'websocket_api', 'usb', 'auth', 'dhcp', 'cloud', 'bluetooth', 'http', 'repairs', 'api', 'zeroconf', 'ssdp'}
2024-05-09 09:29:19.800 INFO (MainThread) [homeassistant.setup] Setting up webhook
2024-05-09 09:29:19.807 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.01 seconds
2024-05-09 09:29:19.811 INFO (MainThread) [homeassistant.setup] Setting up network
2024-05-09 09:29:19.822 INFO (MainThread) [homeassistant.setup] Setup of domain network took 0.01 seconds
2024-05-09 09:29:19.844 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of aiodhcpwatcher==1.0.0
2024-05-09 09:29:19.866 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-1' coro=<setup_and_run_hass() running at /workspaces/core/homeassistant/runner.py:156> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/tasks.py:712> cb=[_run_until_complete_cb() at /usr/local/lib/python3.12/asyncio/base_events.py:182] created at /usr/local/lib/python3.12/asyncio/tasks.py:695> took 0.120 seconds
2024-05-09 09:29:19.877 INFO (MainThread) [asyncio] <Server sockets=(<asyncio.TransportSocket fd=11, family=2, type=1, proto=6, laddr=('0.0.0.0', 8123)>, <asyncio.TransportSocket fd=12, family=10, type=1, proto=6, laddr=('::', 8123, 0, 0)>)> is serving
2024-05-09 09:29:19.882 INFO (MainThread) [homeassistant.components.http] Now listening on port 8123
2024-05-09 09:29:19.888 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.19 seconds
2024-05-09 09:30:22.612 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of aiodiscover==2.1.0
2024-05-09 09:31:19.945 WARNING (MainThread) [asyncio] Executing <TimerHandle when=59698.131316939 _GlobalTaskContext._on_timeout() created at /workspaces/core/homeassistant/util/timeout.py:204> took 0.126 seconds
2024-05-09 09:32:03.904 WARNING (MainThread) [asyncio] Executing <TimerHandle when=59741.851850228 _WatchPendingSetups._async_watch() created at /workspaces/core/homeassistant/bootstrap.py:710> took 0.293 seconds
2024-05-09 09:32:21.783 WARNING (MainThread) [asyncio] Executing <TimerHandle cancelled when=59758.22188509 Store._async_schedule_callback_delayed_write() created at /workspaces/core/homeassistant/helpers/storage.py:458> took 1.902 seconds
2024-05-09 09:32:22.162 WARNING (MainThread) [asyncio] Executing <TimerHandle when=59758.485519545 _set_result_unless_cancelled(<Future finish...events.py:449>, None) at /usr/local/lib/python3.12/asyncio/futures.py:311 created at /usr/local/lib/python3.12/asyncio/tasks.py:661> took 0.119 seconds
2024-05-09 09:32:22.775 WARNING (MainThread) [asyncio] Executing <Task finished name='Task-36' coro=<_GlobalTaskContext._on_wait() done, defined at /workspaces/core/homeassistant/util/timeout.py:244> result=None created at /usr/local/lib/python3.12/asyncio/tasks.py:420> took 0.559 seconds
2024-05-09 09:32:23.022 WARNING (MainThread) [asyncio] Executing <Task cancelled name='setup component dhcp' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> created at /workspaces/core/homeassistant/util/async_.py:40> took 0.212 seconds
2024-05-09 09:32:23.771 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 1 waiting on set() - moving forward
2024-05-09 09:32:23.996 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'intent', 'scene', 'image_upload', 'backup', 'default_config', 'zone', 'onboarding', 'schedule', 'search', 'homeassistant_alerts', 'mobile_app', 'stream', 'input_number', 'logbook', 'my', 'sun', 'input_button', 'wake_word', 'diagnostics', 'conversation', 'map', 'blueprint', 'automation', 'media_source', 'script', 'tts', 'stt', 'ffmpeg', 'shopping_list', 'input_datetime', 'counter', 'system_health', 'history', 'person', 'file_upload', 'assist_pipeline', 'trace', 'input_select', 'input_text', 'application_credentials', 'timer', 'lovelace', 'device_automation', 'config', 'analytics', 'hardware', 'tag', 'input_boolean', 'python_script', 'energy'}
2024-05-09 09:32:24.346 INFO (MainThread) [homeassistant.setup] Setting up scene
2024-05-09 09:32:26.058 INFO (MainThread) [homeassistant.components.scene] Setting up homeassistant.scene
2024-05-09 09:32:26.720 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 1.42 seconds
2024-05-09 09:32:30.776 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of ha-ffmpeg==3.2.0
2024-05-09 09:32:34.786 INFO (MainThread) [homeassistant.setup] Setting up history
2024-05-09 09:32:38.758 INFO (MainThread) [homeassistant.setup] Setup of domain history took 3.90 seconds
2024-05-09 09:32:40.661 INFO (MainThread) [homeassistant.setup] Setting up logbook
2024-05-09 09:32:40.977 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.31 seconds
2024-05-09 09:32:41.194 INFO (MainThread) [homeassistant.setup] Setting up zone
2024-05-09 09:32:41.653 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.46 seconds
2024-05-09 09:32:41.666 INFO (MainThread) [homeassistant.setup] Setting up system_health
2024-05-09 09:32:41.719 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.05 seconds
2024-05-09 09:32:41.955 INFO (MainThread) [homeassistant.setup] Setting up trace
2024-05-09 09:32:42.082 INFO (MainThread) [homeassistant.setup] Setup of domain trace took 0.13 seconds
2024-05-09 09:32:42.116 INFO (MainThread) [homeassistant.setup] Setting up input_number
2024-05-09 09:32:42.194 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 0.08 seconds
2024-05-09 09:32:42.246 INFO (MainThread) [homeassistant.setup] Setting up blueprint
2024-05-09 09:32:42.257 INFO (MainThread) [homeassistant.setup] Setup of domain blueprint took 0.01 seconds
2024-05-09 09:32:42.451 INFO (MainThread) [homeassistant.setup] Setting up automation
2024-05-09 09:32:42.756 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.29 seconds
2024-05-09 09:32:43.237 INFO (MainThread) [homeassistant.setup] Setting up script
2024-05-09 09:32:43.476 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.24 seconds
2024-05-09 09:32:43.568 WARNING (MainThread) [asyncio] Executing <Task cancelling name='Task-1' coro=<setup_and_run_hass() running at /workspaces/core/homeassistant/runner.py:156> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/tasks.py:712> cb=[_run_until_complete_cb() at /usr/local/lib/python3.12/asyncio/base_events.py:182] created at /usr/local/lib/python3.12/asyncio/tasks.py:695> took 19.980 seconds
2024-05-09 09:32:43.657 INFO (MainThread) [homeassistant.setup] Setting up wake_word
2024-05-09 09:32:43.672 INFO (MainThread) [homeassistant.setup] Setup of domain wake_word took 0.01 seconds
2024-05-09 09:32:43.686 INFO (MainThread) [homeassistant.setup] Setting up intent
2024-05-09 09:32:43.885 INFO (MainThread) [homeassistant.setup] Setup of domain intent took 0.18 seconds
2024-05-09 09:32:43.914 WARNING (MainThread) [asyncio] Executing <Task finished name='setup intent as dependency of conversation' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.236 seconds
2024-05-09 09:32:43.915 INFO (MainThread) [homeassistant.setup] Setting up stt
2024-05-09 09:32:43.922 INFO (MainThread) [homeassistant.setup] Setup of domain stt took 0.01 seconds
2024-05-09 09:32:43.923 INFO (MainThread) [homeassistant.setup] Setting up input_datetime
2024-05-09 09:32:44.046 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 0.12 seconds
2024-05-09 09:32:44.051 WARNING (MainThread) [asyncio] Executing <Task finished name='setup component input_datetime' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.128 seconds
2024-05-09 09:32:44.053 INFO (MainThread) [homeassistant.setup] Setting up energy
2024-05-09 09:32:44.099 INFO (MainThread) [homeassistant.setup] Setting up sensor
2024-05-09 09:32:44.188 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.05 seconds
2024-05-09 09:32:44.307 INFO (MainThread) [homeassistant.setup] Setup of domain energy took 0.25 seconds
2024-05-09 09:32:44.308 WARNING (MainThread) [asyncio] Executing <Task finished name='setup energy as dependency of default_config' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.256 seconds
2024-05-09 09:32:44.313 INFO (MainThread) [homeassistant.setup] Setting up homeassistant_alerts
2024-05-09 09:32:44.494 INFO (MainThread) [homeassistant.setup] Setup of domain homeassistant_alerts took 0.18 seconds
2024-05-09 09:32:44.529 WARNING (MainThread) [asyncio] Executing <Task finished name='setup homeassistant_alerts as dependency of default_config' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.220 seconds
2024-05-09 09:32:44.551 INFO (MainThread) [homeassistant.setup] Setting up map
2024-05-09 09:32:44.582 INFO (MainThread) [homeassistant.setup] Setup of domain map took 0.02 seconds
2024-05-09 09:32:44.587 INFO (MainThread) [homeassistant.setup] Setting up media_source
2024-05-09 09:32:44.693 INFO (MainThread) [homeassistant.setup] Setup of domain media_source took 0.11 seconds
2024-05-09 09:32:44.721 WARNING (MainThread) [asyncio] Executing <Task finished name='setup media_source as dependency of default_config' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.135 seconds
2024-05-09 09:32:44.721 INFO (MainThread) [homeassistant.setup] Setting up tag
2024-05-09 09:32:44.786 INFO (MainThread) [homeassistant.setup] Setup of domain tag took 0.06 seconds
2024-05-09 09:32:44.789 INFO (MainThread) [homeassistant.setup] Setting up my
2024-05-09 09:32:44.793 INFO (MainThread) [homeassistant.setup] Setup of domain my took 0.00 seconds
2024-05-09 09:32:44.799 INFO (MainThread) [homeassistant.setup] Setting up sun
2024-05-09 09:32:44.825 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.01 seconds
2024-05-09 09:32:45.327 INFO (MainThread) [homeassistant.components.sensor] Setting up sun.sensor
2024-05-09 09:32:45.516 WARNING (MainThread) [asyncio] Executing <Task finished name='setup sun as dependency of default_config' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.718 seconds
2024-05-09 09:32:45.520 INFO (MainThread) [homeassistant.setup] Setting up counter
2024-05-09 09:32:45.584 INFO (MainThread) [homeassistant.setup] Setup of domain counter took 0.06 seconds
2024-05-09 09:32:45.651 INFO (MainThread) [homeassistant.setup] Setting up schedule
2024-05-09 09:32:45.720 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 0.07 seconds
2024-05-09 09:32:45.750 INFO (MainThread) [homeassistant.setup] Setting up input_select
2024-05-09 09:32:45.854 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component input_select' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/tasks.py:712> cb=[set.remove(), gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.103 seconds
2024-05-09 09:32:45.857 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2024-05-09 09:32:45.922 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 0.06 seconds
2024-05-09 09:32:45.923 INFO (MainThread) [homeassistant.setup] Setting up input_text
2024-05-09 09:32:45.955 INFO (MainThread) [homeassistant.setup] Setting up application_credentials
2024-05-09 09:32:45.978 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 0.02 seconds
2024-05-09 09:32:45.980 INFO (MainThread) [homeassistant.setup] Setting up timer
2024-05-09 09:32:46.022 INFO (MainThread) [homeassistant.setup] Setup of domain timer took 0.04 seconds
2024-05-09 09:32:46.037 INFO (MainThread) [homeassistant.setup] Setting up input_button
2024-05-09 09:32:46.103 INFO (MainThread) [homeassistant.setup] Setting up hardware
2024-05-09 09:32:46.249 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component hardware' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[set.remove(), gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.146 seconds
2024-05-09 09:32:46.252 INFO (MainThread) [homeassistant.setup] Setting up shopping_list
2024-05-09 09:32:46.253 INFO (MainThread) [homeassistant.setup] Setup of domain shopping_list took 0.00 seconds
2024-05-09 09:32:46.735 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component shopping_list' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/tasks.py:712> cb=[set.remove(), gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.482 seconds
2024-05-09 09:32:46.752 INFO (MainThread) [homeassistant.components.sensor] Setting up energy.sensor
2024-05-09 09:32:47.223 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 1.47 seconds
2024-05-09 09:32:47.258 WARNING (MainThread) [asyncio] Executing <Task finished name='setup component input_select' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.251 seconds
2024-05-09 09:32:47.268 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 1.34 seconds
2024-05-09 09:32:47.337 INFO (MainThread) [homeassistant.setup] Setup of domain input_button took 1.30 seconds
2024-05-09 09:32:47.567 WARNING (MainThread) [asyncio] Executing <Task pending name='config entry setup Shopping list shopping_list 9ae31b36c4bb510a6e20e568275f5f15' coro=<ConfigEntry.async_setup_locked() running at /workspaces/core/homeassistant/config_entries.py:715> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.202 seconds
2024-05-09 09:32:47.593 INFO (MainThread) [homeassistant.setup] Setting up analytics
2024-05-09 09:32:49.694 INFO (MainThread) [homeassistant.setup] Setup of domain analytics took 2.10 seconds
2024-05-09 09:32:49.696 WARNING (MainThread) [asyncio] Executing <Task finished name='setup component analytics' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 2.104 seconds
2024-05-09 09:32:49.704 INFO (MainThread) [homeassistant.setup] Setting up todo
2024-05-09 09:32:49.713 INFO (MainThread) [homeassistant.setup] Setup of domain todo took 0.01 seconds
2024-05-09 09:32:49.718 INFO (MainThread) [homeassistant.components.todo] Setting up shopping_list.todo
2024-05-09 09:32:49.874 WARNING (MainThread) [asyncio] Executing <Task finished name='config entry setup Shopping list shopping_list 9ae31b36c4bb510a6e20e568275f5f15' coro=<ConfigEntry.async_setup_locked() done, defined at /workspaces/core/homeassistant/config_entries.py:710> result=None created at /workspaces/core/homeassistant/util/async_.py:40> took 0.175 seconds
2024-05-09 09:32:49.874 INFO (MainThread) [homeassistant.setup] Setup of domain hardware took 3.77 seconds
2024-05-09 09:33:02.131 INFO (SyncWorker_3) [homeassistant.util.package] Attempting install of securetar==2024.2.1
2024-05-09 09:33:02.281 INFO (MainThread) [homeassistant.setup] Setting up ffmpeg
2024-05-09 09:33:02.494 WARNING (MainThread) [asyncio] Executing <Task pending name='setup ffmpeg as dependency of tts' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.213 seconds
2024-05-09 09:33:02.572 INFO (MainThread) [asyncio] execute program 'ffmpeg': <_UnixSubprocessTransport pid=2811 running stdin=<_UnixWritePipeTransport fd=14 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=19 polling>>
2024-05-09 09:33:10.518 INFO (MainThread) [asyncio] <_UnixReadPipeTransport fd=19 polling> was closed by peer
2024-05-09 09:33:10.547 INFO (MainThread) [asyncio] <_UnixSubprocessTransport pid=2811 running stdin=<_UnixWritePipeTransport closed fd=14 closed> stdout=<_UnixReadPipeTransport closed fd=19 closed>> exited with return code 0
2024-05-09 09:33:10.561 INFO (MainThread) [homeassistant.setup] Setup of domain ffmpeg took 8.28 seconds
2024-05-09 09:33:12.827 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of PyTurboJPEG==1.7.1
2024-05-09 09:33:13.073 INFO (MainThread) [homeassistant.setup] Setting up backup
2024-05-09 09:33:13.083 INFO (MainThread) [homeassistant.setup] Setup of domain backup took 0.01 seconds
2024-05-09 09:33:34.527 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of ha-av==10.1.1
2024-05-09 09:33:58.687 WARNING (MainThread) [asyncio] Executing <Task pending name='setup stream as dependency of default_config' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.110 seconds
2024-05-09 09:33:59.176 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of RestrictedPython==7.0
2024-05-09 09:33:59.186 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component python_script' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[set.remove(), gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.155 seconds
2024-05-09 09:34:09.012 WARNING (MainThread) [asyncio] Executing <TimerHandle cancelled when=59865.826135699 _weakref_handle((<weakref at 0...x7f5f7e4bdee0>, '_cleanup_closed')) at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:592 created at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:612> took 0.110 seconds
2024-05-09 09:34:10.919 INFO (MainThread) [homeassistant.setup] Setting up stream
2024-05-09 09:34:11.344 WARNING (MainThread) [asyncio] Executing <Task pending name='setup stream as dependency of default_config' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.466 seconds
2024-05-09 09:34:11.947 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.97 seconds
2024-05-09 09:34:12.279 WARNING (MainThread) [asyncio] Executing <Task finished name='setup stream as dependency of default_config' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.906 seconds
2024-05-09 09:34:17.551 WARNING (MainThread) [asyncio] Executing <TimerHandle cancelled when=59875.733894245 _weakref_handle((<weakref at 0...x7f5f7e4bdee0>, '_cleanup_closed')) at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:592 created at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:612> took 0.179 seconds
2024-05-09 09:34:22.075 INFO (SyncWorker_3) [homeassistant.util.package] Attempting install of hassil==1.6.1
2024-05-09 09:34:22.306 INFO (MainThread) [homeassistant.setup] Setting up python_script
2024-05-09 09:34:22.451 INFO (MainThread) [homeassistant.setup] Setup of domain python_script took 0.13 seconds
2024-05-09 09:34:51.129 INFO (SyncWorker_3) [homeassistant.util.package] Attempting install of home-assistant-intents==2024.4.24
2024-05-09 09:35:01.696 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component conversation' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[set.remove(), gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.182 seconds
2024-05-09 09:35:01.934 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of mutagen==1.47.0
2024-05-09 09:35:05.224 WARNING (MainThread) [asyncio] Executing <TimerHandle when=59921.201610097 _WatchPendingSetups._async_watch() created at /workspaces/core/homeassistant/bootstrap.py:710> took 0.263 seconds
2024-05-09 09:35:09.473 INFO (MainThread) [homeassistant.setup] Setting up conversation
2024-05-09 09:35:10.064 ERROR (MainThread) [homeassistant.setup] Error during setup of component conversation
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/workspaces/core/homeassistant/components/conversation/__init__.py", line 193, in async_setup
    from homeassistant.components.assist_pipeline import (  # pylint: disable=import-outside-toplevel
  File "/workspaces/core/homeassistant/components/assist_pipeline/__init__.py", line 21, in <module>
    from .pipeline import (
  File "/workspaces/core/homeassistant/components/assist_pipeline/pipeline.py", line 24, in <module>
    from homeassistant.components import (
  File "/workspaces/core/homeassistant/components/tts/__init__.py", line 22, in <module>
    import mutagen
ModuleNotFoundError: No module named 'mutagen'
2024-05-09 09:35:10.177 INFO (MainThread) [homeassistant.setup] Setup of domain conversation took 0.66 seconds
2024-05-09 09:35:10.196 WARNING (MainThread) [asyncio] Executing <Task finished name='setup component conversation' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=False created at /workspaces/core/homeassistant/util/async_.py:40> took 0.731 seconds
2024-05-09 09:35:28.120 WARNING (MainThread) [asyncio] Executing <Task pending name='setup component tts' coro=<async_setup_component() running at /workspaces/core/homeassistant/setup.py:166> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[set.remove(), gather.<locals>._done_callback() at /usr/local/lib/python3.12/asyncio/tasks.py:767] created at /workspaces/core/homeassistant/util/async_.py:40> took 0.168 seconds
2024-05-09 09:35:28.147 INFO (SyncWorker_1) [homeassistant.util.package] Attempting install of PyNaCl==1.5.0
2024-05-09 09:35:28.693 INFO (MainThread) [homeassistant.setup] Setting up tts
2024-05-09 09:35:29.310 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.62 seconds
2024-05-09 09:35:29.802 WARNING (MainThread) [asyncio] Executing <Task finished name='setup component tts' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=True created at /workspaces/core/homeassistant/util/async_.py:40> took 0.683 seconds
2024-05-09 09:35:29.835 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'assist_pipeline'. Setup failed for dependencies: ['conversation']
2024-05-09 09:35:29.951 ERROR (MainThread) [homeassistant.setup] Setup failed for 'assist_pipeline': Could not setup dependencies: conversation
2024-05-09 09:35:29.964 WARNING (MainThread) [asyncio] Executing <Task finished name='setup assist_pipeline as dependency of default_config' coro=<async_setup_component() done, defined at /workspaces/core/homeassistant/setup.py:142> result=False created at /workspaces/core/homeassistant/util/async_.py:40> took 0.161 seconds
2024-05-09 09:35:39.542 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2024-05-09 09:35:39.549 INFO (MainThread) [homeassistant.setup] Setting up notify
2024-05-09 09:35:39.552 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.00 seconds
2024-05-09 09:35:39.556 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.01 seconds
2024-05-09 09:35:39.562 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2024-05-09 09:35:39.566 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration default_config - received exception
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/setup.py", line 166, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/setup.py", line 314, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/workspaces/core/homeassistant/setup.py", line 559, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/workspaces/core/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/requirements.py", line 176, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/workspaces/core/homeassistant/requirements.py", line 192, in _async_process_integration
    await self.async_process_requirements(
  File "/workspaces/core/homeassistant/requirements.py", line 276, in async_process_requirements
    async with self.pip_lock:
  File "/usr/local/lib/python3.12/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.12/asyncio/locks.py", line 113, in acquire
    await fut
asyncio.exceptions.CancelledError: Global task timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/core/homeassistant/setup.py", line 186, in async_setup_component
    await future
  File "/workspaces/core/homeassistant/setup.py", line 186, in async_setup_component
    await future
  File "/workspaces/core/homeassistant/setup.py", line 166, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/setup.py", line 314, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/workspaces/core/homeassistant/setup.py", line 555, in async_process_deps_reqs
    if failed_deps := await _async_process_dependencies(hass, config, integration):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/setup.py", line 239, in _async_process_dependencies
    results = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/setup.py", line 186, in async_setup_component
    await future
  File "/workspaces/core/homeassistant/setup.py", line 186, in async_setup_component
    await future
  File "/workspaces/core/homeassistant/setup.py", line 166, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/setup.py", line 314, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/workspaces/core/homeassistant/setup.py", line 555, in async_process_deps_reqs
    if failed_deps := await _async_process_dependencies(hass, config, integration):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/setup.py", line 239, in _async_process_dependencies
    results = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/core/homeassistant/setup.py", line 181, in async_setup_component
    future.set_exception(err)
asyncio.exceptions.InvalidStateError: invalid state
2024-05-09 09:35:39.583 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 430.75s
2024-05-09 09:35:39.585 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2024-05-09 09:36:45.765 WARNING (MainThread) [asyncio] Executing <TimerHandle when=60023.66539185853 _TrackPointUTCTime(hass=<HomeAssistant RUNNING>, job=<Job track point in utc time 2024-05-09 09:36:45.241855+00:00 HassJobType.Callback <bound method Sun.update_sun_position of <entity unknown.unknown=unknown>>>, utc_point_in_time=datetime.datetime(2024, 5, 9, 9, 36, 45, 241855, tzinfo=datetime.timezone.utc), expected_fire_timestamp=1715247405.241855, _cancel_callback=<TimerHandle when=60023.66539185853 ...() created at /workspaces/core/homeassistant/helpers/event.py:1459>)() created at /workspaces/core/homeassistant/helpers/event.py:1459> took 0.227 seconds
2024-05-09 09:36:53.016 WARNING (MainThread) [asyncio] Executing <TimerHandle cancelled when=60028.342100295 _weakref_handle((<weakref at 0...x7f5f7e4bdee0>, '_cleanup_closed')) at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:592 created at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:612> took 3.025 seconds
2024-05-09 09:36:57.419 WARNING (MainThread) [asyncio] Executing <TimerHandle cancelled when=60030.815654035 _weakref_handle((<weakref at 0...x7f5f7e4bdee0>, '_cleanup_closed')) at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:592 created at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:612> took 0.195 seconds
2024-05-09 09:36:57.734 WARNING (MainThread) [asyncio] Executing <TimerHandle when=60033.367532214 _run_async_call_action(<HomeAssistant RUNNING>, <Job Recorder...t.py:1524>>)>>) at /workspaces/core/homeassistant/helpers/event.py:1500 created at /workspaces/core/homeassistant/helpers/event.py:1524> took 0.122 seconds
2024-05-09 09:37:01.502 WARNING (MainThread) [asyncio] Executing <TimerHandle cancelled when=60039.659448124 _weakref_handle((<weakref at 0...x7f5f7e4bdee0>, '_cleanup_closed')) at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:592 created at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:612> took 0.216 seconds
2024-05-09 09:38:58.147 WARNING (MainThread) [asyncio] Executing <TimerHandle cancelled when=60155.929859527 _weakref_handle((<weakref at 0...x7f5f7e4bdee0>, '_cleanup_closed')) at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:592 created at /usr/local/lib/python3.12/site-packages/aiohttp/helpers.py:612> took 0.105 seconds
2024-05-09 09:39:02.250 WARNING (MainThread) [asyncio] Executing <TimerHandle when=60156.005598061 _run_async_call_action(<HomeAssistant RUNNING>, <Job Recorder...t.py:1524>>)>>) at /workspaces/core/homeassistant/helpers/event.py:1500 created at /workspaces/core/homeassistant/helpers/event.py:1524> took 1.970 seconds
2024-05-09 09:40:45.577 WARNING (MainThread) [asyncio] Executing <TimerHandle when=60263.72443656978 _TrackPointUTCTime(hass=<HomeAssistant RUNNING>, job=<Job track point in utc time 2024-05-09 09:40:45.276096+00:00 HassJobType.Callback <bound method Sun.update_sun_position of <entity unknown.unknown=unknown>>>, utc_point_in_time=datetime.datetime(2024, 5, 9, 9, 40, 45, 276096, tzinfo=datetime.timezone.utc), expected_fire_timestamp=1715247645.276096, _cancel_callback=<TimerHandle when=60263.72443656978 ...() created at /workspaces/core/homeassistant/helpers/event.py:1459>)() created at /workspaces/core/homeassistant/helpers/event.py:1459> took 0.213 seconds
2024-05-09 09:41:03.708 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-68' coro=<HomeAssistant.async_stop() running at /workspaces/core/homeassistant/core.py:1154> created at /usr/local/lib/python3.12/asyncio/tasks.py:420> took 0.428 seconds
2024-05-09 09:41:04.214 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-68' coro=<HomeAssistant.async_stop() running at /workspaces/core/homeassistant/core.py:1167> created at /usr/local/lib/python3.12/asyncio/tasks.py:420> took 0.412 seconds
2024-05-09 09:41:04.446 INFO (Recorder) [homeassistant.components.recorder.pool.RecorderPool] Pool recreating
